version: '3'

services:
  db:
    container_name: commitAir
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: commitAir12345
      MYSQL_DATABASE: commmit-air-db

    networks:
      - my-network

    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: redis:5.0.3
    restart: unless-stopped

    networks:
      - my-network

    ports:
      - "6379:6379"

networks:
  my-network:
    driver: bridge